import { gridconfig, columnconfig, cellconfig } from './index'
import { Typography } from 'goobs-repo'
import React from 'react'

export const defaultGridConfig: gridconfig = {
  gridname: 'testgrid',
  alignment: 'center',
  margintop: 10,
  marginbottom: 2,
  marginright: 2,
  marginleft: 10,
  animation: 'none',
  gridwidth: '100%',
}

export const defaultColumnConfig: columnconfig[] = [
  {
    row: 1,
    column: 1,
    gridname: 'testgrid',
    alignment: 'left',
    columnwidth: '33.33%',
    margintop: 1,
    marginbottom: 1,
    marginright: 0,
    marginleft: 0,
    animation: 'none',
    component: <Typography variant="h4" text="Column 1" />,
    cellconfig: {
      border: 'none',
      mobilewidth: '100%',
      tabletwidth: '33.33%',
      computerwidth: '33.33%',
    },
  },
  {
    row: 1,
    column: 2,
    gridname: 'testgrid',
    alignment: 'left',
    columnwidth: '33.33%',
    margintop: 1,
    marginbottom: 1,
    marginright: 0,
    marginleft: 0,
    animation: 'none',
    component: <Typography variant="h4" text="Column 2" />,
    cellconfig: {
      border: 'none',
      mobilewidth: '100%',
      tabletwidth: '33.33%',
      computerwidth: '33.33%',
    },
  },
  {
    row: 1,
    column: 3,
    gridname: 'testgrid',
    alignment: 'left',
    columnwidth: '33.33%',
    margintop: 1,
    marginbottom: 1,
    marginright: 0,
    marginleft: 0,
    animation: 'none',
    component: <Typography variant="h4" text="Column 3" />,
    cellconfig: {
      border: 'none',
      mobilewidth: '100%',
      tabletwidth: '33.33%',
      computerwidth: '33.33%',
    },
  },
  {
    row: 2,
    column: 1,
    gridname: 'testgrid',
    alignment: 'center',
    columnwidth: '33.33%',
    margintop: 1,
    marginbottom: 1,
    marginright: 2,
    marginleft: 2,
    animation: 'none',
    component: <Typography variant="h4" text="Column 4" />,
    cellconfig: {
      border: 'none',
      mobilewidth: '100%',
      tabletwidth: '33.33%',
      computerwidth: '33.33%',
    },
  },
  {
    row: 2,
    column: 2,
    gridname: 'testgrid',
    alignment: 'center',
    columnwidth: '33.33%',
    margintop: 1,
    marginbottom: 1,
    marginright: 2,
    marginleft: 2,
    animation: 'none',
    component: <Typography variant="h4" text="Column 5" />,
    cellconfig: {
      border: 'none',
      mobilewidth: '100%',
      tabletwidth: '33.33%',
      computerwidth: '33.33%',
    },
  },
  {
    row: 2,
    column: 3,
    gridname: 'testgrid',
    alignment: 'center',
    columnwidth: '33.33%',
    margintop: 1,
    marginbottom: 1,
    marginright: 0,
    marginleft: 0,
    animation: 'none',
    component: <Typography variant="h4" text="Column 6" />,
    cellconfig: {
      border: 'none',
      mobilewidth: '100%',
      tabletwidth: '33.33%',
      computerwidth: '33.33%',
    },
  },
]

export const defaultCellConfig: cellconfig = {
  border: 'none',
  mobilewidth: '100%',
  tabletwidth: '100%',
  computerwidth: '100%',
}
